[general]
import = [
  "~/.config/alacritty/keybind.toml",
  "~/.config/alacritty/nord.toml",
  # "~/.config/alacritty/rose-pine-dawn.toml",
]


[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
style = "Light"
# style = "Regular"
# family = "Hack Nerd Font Mono"
# family = "JetBrainsMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
family = "BlexMono Nerd Font"
# family = "FiraCode Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true

[window.padding]
x = 0
y = 0

[keyboard]

