backend = "glx";
opacity = true;

inactive-opacity = 0.8;
focused-opacity = 1;
opacity-rule = [
  "87:class_g = 'Alacritty'",
  "87:class_g = 'org.wezfurlong.wezterm'"
];

# Enable and set rounded corners
corner-radius = 10
shadow-radius = 15

# Enable shadows
shadow = true
no-dock-shadow = true

# Gap settings for floating windows
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'toolbar'"
];

