backend = "glx";
opacity = true;

inactive-opacity = 0.9;
focused-opacity = 1;

opacity-rule = [
  "0:title *= 'Picture-in-picture'", 
  "0:!focused && title *= 'Picture-in-picture'", 
];

opacity-rule = [
  "93:class_g = 'Alacritty'",
  "93:class_g = 'org.wezfurlong.wezterm'",
];

# Enable and set rounded corners
corner-radius = 8
shadow-radius = 15

# Enable shadows
shadow = true
no-dock-shadow = true

# Gap settings for floating windows
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'toolbar'"
];

