#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#   "rich>=14.0.0",
# ]
# ///

import socket
import getpass

def get_local_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))  
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "N/A"


def display_info():
    user = getpass.getuser()
    hostname = socket.gethostname()
    ip = get_local_ip()
    
    print(f"User: {user} | Hostname: {hostname} | IP: {ip}")
    # while True:
    #     print(f"User: {user} | Hostname: {hostname} | IP: {ip}", end='\r', flush=True)
    #     time.sleep(60) 

if __name__ == "__main__":
    display_info()
