require("plugins.lazy")

require("plugins.lualine")
require("plugins.mini-indentscope").setup()
require("plugins.toggle-term")
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.telescope")
require("plugins.gitsigns").setup()
require("plugins.lsp")
require("plugins.autocmp")
require("plugins.conform")
require("plugins.obsidian").setup()

require("config.options")
require("config.autocmd")
require("config.keymaps")
