;# DEFAULT
[colors]
; background = #282A2E
; background-alt = #373B41
; foreground = #C5C8C6
; primary = #F0C674
; secondary = #8ABEB7
; alert = #A54242
; disabled = #707880

# background          = #1a1b26
# background-alt      = #1a1b26
# foreground          = #a9b1d6
# primary             = #9ece6a
# secondary         = #ad8ee6
# alert = #bd2c40
# disabled = #707880

# ROSE PINE
background = #191724
background-alt = #21202e
primary = #ebbcba
secondary = #f6c177	
alert = #eb6f92

# # NORD
# background = #2E3440
# foreground = #D8DEE9
# primary = #81A1C1
# secondary = #88C0D0
# alert = #BF616A
# success = #A3BE8C
# warning = #EBCB8B
# highlight = #B48EAD



;;# Tokyo-night
;[colors]
;background      = #1a1b26
;foreground      = #a9b1d6
;foreground2     = #bbc2cf
;black           = #32344a
;red             = #f7768e
;green           = #9ece6a
;yellow          = #ebcb8c
;blue            = #7aa2f7
;magenta         = #ad8ee6
;cyan            = #449dab
;white           = #e5e9f0
;alert = #bd2c40


;# Tokyo-night-storm
; [colors]
; foreground      = #a9b1d6
; foreground2     = #bbc2cf
; background      = #24283b
; black           = #414868
; red             = #f7768e
; green           = #9ece6a
; yellow          = #e0af68
; blue            = #7aa2f7
; magenta         = #bb9af7
; cyan            = #7dcfff
; white           = #e5e9f0
; alert           = #bd2c40

